# python-ci.yml
name: basic CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run-pytest:
    runs-on: ubuntu-latest

    steps:
    # First step: checkout to the branch that triggered the event
    - uses: actions/checkout@v4

    # install uv
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    # set up Python
    - name: Set up Python
      run: uv python install 3.12

    # install dependencies with
    - name: Install dependencies
      run: uv sync

    # run tests with pytest
    - name: Run tests
      run: uv run pytest
